### ISSUE TITLE
ansi_term formatting should be disabled on Windows

### ISSUE THREAD

**Issue by sbercx** [rust-alt/cargo-esr#2]
ansi_term formatting should be disabled on Windows, otherwise the output will look like this:
![xgtnahq](https://cloud.githubusercontent.com/assets/20236798/22380842/5bcd1d0a-e4bf-11e6-9ba1-875bee0773f4.png)

**Comment by MoSal** [comment]
Thank you for reporting this.

You can pass `-n/--no-color` to disable formatted output.

Users of [ConEmu](https://github.com/Maximus5/ConEmu)(recommended), or [ansicon](https://github.com/adoxa/ansicon), will get the right output. And I don't think it's fair to regress their experience.

If there is a way to get this right in all platforms, without regressing the experience of anyone, pointers
in the right direction would be most welcome.

**Comment by MoSal** [comment]
@sbxx  If you're still around. Can you test the `term-painter` branch?

It's supposed to support native formatting in Windows console.

**Comment by sbercx** [comment]
Just tested it. I'm getting colored output in the native console. 👍

**Comment by MoSal** [comment]
Pushed to master with a small fix-up.

Thank you for reporting this, and for taking the time to test the migration to `term-painter`.
